neu-self-image-experiments/sie-firebase

src/scss/_base.scss, src/scss/_colors.scss, src/scss/_functions.scss, src/scss/_typography.scss, src/stories/components/Button/styles.scss
- Update Teal color
- Update variable names
- Update px to rem conversion
=> Quick FE updates to variables and colors

src/stories/components/HorizontalTitle/HorizontalTitle.js, src/stories/components/HorizontalTitle/HorizontalTitle.stories.js, src/stories/components/HorizontalTitle/styles.scss
~~ Jira task [here](https://cs6510.atlassian.net/browse/SIE-47?atlOrigin=eyJpIjoiYWI0MjI4YTQxZDQ5NGY1NmJmNjllZDk3MzAzOGNmY2YiLCJwIjoiaiJ9) ~~
Screenshot:
=> SIE-47 Added horizontal-title component

src/stories/components/Button/Button.js, src/stories/components/Button/Button.stories.js, src/stories/components/Button/styles.scss
- Buttons come in the following styles: Primary, Secondary, Tertiary, Quaternary 
- All four styles variants include a "Small Text" variant
- Jira task: [SIE-8 Buttons]( https://cs6510.atlassian.net/browse/SIE-8)
=> Adding Quaternary button and small button variations

src/stories/components/Section/Section.js, src/stories/components/Section/Section.stories.js, src/stories/components/Section/styles.scss
The section component has the following fields:
- HTML Title Element (i.e. <{TitleEl ? TitleEl : ‘h3'}>)
- Title 
- Content 
- ModifierClass (in case we need manipulate the font size of the paragraphs)
https://cs6510.atlassian.net/browse/SIE-13?atlOrigin=eyJpIjoiMGU0ODkzYzg2OTVlNDM5NDlhMDQ4NDllNWExNzE3M2UiLCJwIjoiaiJ9
=> [SIE-13-section] Implementing section component

public/index.html, src/firebase/CRUDServices/userServices.js, src/firebase/firebase.js
Here is the user crud skeleton for now. Please review. Thanks!
=> SIE-40 created CRUD-user and updated firebase.js and index.html

src/firebase/CRUDServices/selfImageExperimentService.js
- defined basic CRUD operations in a separate selfImageExperimentService.js
=> add self image CRUD service

src/firebase/CRUDServices/experimentServices.js
1. Remove all console.log and console.error as requested.
2. Leave the error handling as return false and empty object/array now. Will update after decide which error handling method to use.
=> sie-41-revice-console-log/error-handling

src/stories/components/Modal/Modal.js, src/stories/components/Modal/Modal.stories.js, src/stories/pages/AddExperiment/AddExperiment.js, src/stories/pages/AddExperiment/AddExperiment.stories.js, src/stories/pages/AddExperiment/AddExperiment.test.js
Missing parts:
1. Tests
2. Saving experiment in firebase
=> SIE-66-Add-New-Experiment

src/scss/_base.scss, src/scss/_spacing.scss, src/stories/components/HorizontalTitle/HorizontalTitle.js, src/stories/components/HorizontalTitle/HorizontalTitle.stories.js, src/stories/components/HorizontalTitle/styles.scss, src/stories/components/Section/Section.stories.js, src/stories/components/Steps/Steps.js, src/stories/layouts/Header/styles.scss, src/stories/layouts/Wizard/Wizard.js, src/stories/layouts/Wizard/styles.scss, src/stories/pages/Experiment/Experiment.js, src/stories/pages/Login/Login.stories.js, src/stories/pages/Signup/Signup.js, src/stories/pages/Signup/Signup.stories.js
Just FYI, a bunch of these changes are indentation and mostly CSS. This is the [ticket](https://cs6510.atlassian.net/browse/SIE-90).
=> Feature/[SIE-90] fix Storybook and clean templates

src/firebase/api/gcp-utils.js, src/firebase/firebase.js
- Define callback function for getting processed images from cloud storage
- Fix the image upload destination issue
- should be firebase.app().storage() instead of firebase.storage
- Update the error handling
Files to review:
- gcp-util.js
- firebase.js
=> define callback for getting images & fix upload

.firebaserc, .gitignore, firebase.json, package.json, public/index.html
Deploy firebase app by running `npm run deploy`
TODO: 
- Web SEO, update icons, etc. Refer to JIRA task [here](https://cs6510.atlassian.net/browse/SIE-130)
=> SIE-91 Deploy firebase app

src/App.js, src/stories/components/MainMenu/MainMenu.js
SIE - 32 / Add Experiments Page to routing
=> Connected ExperimentsPage to Main Menu

public/index.html, src/external_libraries/jspsych-6.3.0/css/jspsych.css, src/external_libraries/jspsych-6.3.0/extensions/jspsych-ext-webgazer.js, src/external_libraries/jspsych-6.3.0/jspsych.js, src/external_libraries/jspsych-6.3.0/license.txt, src/external_libraries/jspsych-6.3.0/plugins/jspsych-html-keyboard-response.js, src/external_libraries/jspsych-6.3.0/plugins/jspsych-image-keyboard-response.js, src/external_libraries/jspsych-6.3.0/plugins/template/jspsych-plugin-template.js
Small PR to add the library, [jsPsych](https://www.jspsych.org/), that we will use to conduct the trials of the experiment. No functional changes contained in this PR. I put the files in `sie-firebase/src/external_libraries/` but if something like `sie-firebase/src/jspsych/` is a better home for the library I can move it no problem.
Note: in future PRs where we actually add the jsPsych experiment functionality (trials and timeline), we will have to add the script(s) of the jsPsych plugin(s) needed. There are at least two ways to do this:
1. Programmatically insert the scripts right before running the experiment ([see example here](https://github.com/neu-self-image-experiments/sie-firebase/pull/72/commits/9895b5d4b412ff0c9f853664d17052b7b5275033#diff-7e2f6b31103a33591df109ac5c9d69bbb87c6ce5 …
=> [SIE-135] Add jsPsych library to project

src/firebase/api/experiments.js, src/firebase/api/users.js
- Added API method in experiment.js for storing experiment result( **jsPsych data** )
- Unified the import statement
=> [SIE-167] Add api method for storing experiment result

src/firebase/api/experiments.js
In the PR:
- Fix the Not_found error while the experiment is not defined under the user document
=> fix store experiment results bug

src/firebase/api/gcp-utils.js
Reformat return JSON format to status, data, error
=> reformat response in gcp-utils

src/firebase/api/gcp-utils.js
Fix csv file name in uploadSelectionResult() to conform to cloud functions backend
=> Fix upload user selection file name issue

src/stories/components/JsPsych/JsPsych.js
Creating a method to transform result data from JsPsych experiment to match model scheme of back end api. Utilizes new backend API 'uploadSelectionResult' via gcp-utils.js 
Confirmed that data gets properly stored in FireBase bucket 'sie-user-selections' as 'result.csv' for this particular user / experiment (Bo0Hka0QT5O2Q026qKpFbAYHOW23-9iG2wajKXkjLXiLQfwgj).
Here are some notes regarding the input / output for the trial experiment: 
- If user makes the 'correct' choice - meaning they chose the original image - it gets counted as a '1' in response column.
- If user makes the 'different' choice - meaning they chose the inverted image - it gets counted as a '-1' in response column.
- If user makes no selection, it gets counted as '-1'.
How I tested:
- Check current data in firebase bucket …
=> Updating saveExperimentData method to refractor data & upload to firebase via new backend API

src/stories/pages/Signup/Signup.js
Added feedback messages for signup to react to user mistakes
https://cs6510.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=SIE&view=planning&selectedIssue=SIE-153&issueLimit=100
=> added feedback messages to signup

src/stories/components/JsPsych/JsPsych.js
Updating static JsPsych instructions to notify user what 'E' and 'I' correlates with. Also leaving a 'Note' instructing user to close experiment window upon completion.
=> Updating JsPsych static instructions

src/stories/components/ImageSelectionTask/ImageSelectionTask.js, src/stories/components/JsPsych/JsPsych.js, src/stories/components/Modal/Modal.js, src/stories/pages/Experiment/Experiment.js
Added `canOpen` and `canClose` to Modal to fix issue where sometimes you can't open and close a Modal if the shared prop wasn't set.
=> Fix Modal open and close
